name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo (full history for branch ops)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate SVG
        id: generate
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug - list dist
        run: |
          echo "== dist contents =="
          ls -la dist || true
          echo "== file info =="
          file dist/* || true
          echo "== head of files =="
          for f in dist/*; do
            echo "---- $f ----"
            head -n 8 "$f" || true
          done

      - name: Ensure output branch exists (create if missing)
        run: |
          git fetch origin output:output || echo "output branch may not exist yet"
          git branch --list

      - name: Copy generated files to repo root (prepare commit)
        run: |
          mkdir -p build-output
          cp -f dist/* build-output/ || true
          ls -la build-output || true

      - name: Commit generated SVG to output branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "chore: update generated snake.svg [skip ci]"
          add: "build-output/*"
          branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
